---
services:
  quark_apps_server:
    image: quark-apps-server:latest
    container_name: quark-apps-server
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      - PORT=8080
      - ADMIN_PORT=9000
      - HOST=0.0.0.0
#      - QUARK_DB_HOST=example.com
      - QUARK_DB_NAME=quark
      - QUARK_DB_USER=quark
      - QUARK_DB_PASS=quarkPassw0rd # Change for production use
    volumes:
      - ./apps:/usr/share/nginx/html/apps:rw
    depends_on:
      - quark_db
  
  quark_db:
    image: mysql:8.0.40-debian
    container_name: quark-apps-server-db
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devPassw0rd! # Change for production use
      MYSQL_DATABASE: quark
      MYSQL_USER: quark
      MYSQL_PASSWORD: quarkPassw0rd # Change for production use
    volumes:
      - ./db:/var/lib/mysql:rw
